image: rust:slim-stretch

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - target/
  - ~/.cargo/

pages:
  script:
  - apt-get update
  - apt-get install -y libssl-dev openssl pkg-config
  - cargo install cargo-web -f
  - cargo web build
  - cp ./target/wasm32-unknown-unknown/release/web-snake.js ./static/
  - cp ./target/wasm32-unknown-unknown/release/web-snake.wasm ./static/
  artifacts:
    paths:
    - static
  only:
  - master
