image: rust:slim-stretch

stages:
  - build
  - deploy

build:
  script:
  - apt-get update
  - apt-get install -y libssl-dev openssl pkg-config
  - cargo install cargo-web -f
  - cargo web build
  - cp ./target/wasm32-unknown-unknown/release/web-snake.js ./static/
  - cp ./target/wasm32-unknown-unknown/release/web-snake.wasm ./static/
  artifacts:
    paths:
    - static
  only:
  - master
  cache:
  - target/
  - $HOME/.cargo

deploy:
  image: python:latest
  only: [master]
  stage: deploy
  dependencies: 
    - build
  script:
  - pip install awscli
  - aws s3 cp ./static/ s3://snake.ahouts.com/ --recursive
  - aws cloudfront create-invalidation --distribution-id E7AID7CR7V4S3 --paths '/*'

