[package]
name = "web-snake"
version = "0.1.0"
authors = ["ahouts <ahouts4@gmail.com>"]

[dependencies]
stdweb = "0.4.8"
brotli = "2.5.0"
serde = "1.0.71"
serde_derive = "1.0.71"
bincode = "1.0.1"
time = "0.1.40"
chrono = { version = "0.4.5", features = ["serde"] }
